/// This class implements SASchema for the DeepSee SubjectArea classes.
Class %DeepSee.Model.SASchemaSubjectArea Extends %Studio.SASchemaClass [ System = 3 ]
{

/// This is the namespace value used to identify this SA schema.
/// This corresponds to the XMLNamespace keyword of a Studio XData block.
Parameter XMLNAMESPACE = "http://www.intersystems.com/subjectarea";

/// This is comma-separated list of the classes whose xml elements
/// can be used as the root level element of a document.
Parameter ROOTCLASSES As STRING = "%DeepSee.Model.SubjectArea.subjectArea:subjectArea";

}
