Class %BI.OCR Extends %Persistent [ ClassType = persistent, LegacyInstanceContext, Not ProcedureBlock, System = 4 ]
{

Storage Default
{
<Data name="OCRDefaultData">
<Value name="1">
<Value>%%CLASSNAME</Value>
</Value>
</Data>
<DataLocation>^BI.OCRD</DataLocation>
<DefaultData>OCRDefaultData</DefaultData>
<IdLocation>^BI.OCRD</IdLocation>
<IndexLocation>^BI.OCRI</IndexLocation>
<StreamLocation>^BI.OCRS</StreamLocation>
<Type>%Library.CacheStorage</Type>
}

}
